name: Sync Notion and Deploy

on:
  schedule:
    - cron: '0 2 * * *'  # 每天北京时间上午10点（UTC+2）
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run fetch script
        run: node notion/fetch.js

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add notion/data/
          git commit -m "chore: sync Notion data [auto]" || exit 0
          git push
