name: Sync Notion and Deploy

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

on:
  schedule:
    - cron: '0 2 * * *'  # 每天北京时间上午10点
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch Notion data
        run: node notion/fetch.js

      - name: Commit & Push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add notion/data/
          git commit -m "chore: auto sync Notion data" || echo "no changes"
          git push
